Update python version required
When using python 3.6.0, I get `AttributeError: module 'typing' has no attribute 'AsyncGenerator'`. In order to resolve, need to use 3.6.1 or greater.